<?php
/**
 * ChannelStatus
 *
 * @package  BigCommerce\Api\v3
 */

/**
 * BigCommerce Channels API
 *
 * The Channels API enables you to create and manage listings across a BigCommerce merchant's sales channels.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BigCommerce\Api\v3\Model;

use \ArrayAccess;

class ChannelStatus {
    const ACTIVE = 'active';
    const PRELAUNCH = 'prelaunch';
    const INACTIVE = 'inactive';
    const CONNECTED = 'connected';
    const DISCONNECTED = 'disconnected';
    const DELETED = 'deleted';
    const TERMINATED = 'terminated';
    

    
}


