<?php
/**
 * UpdateListingRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BigCommerce\Api\v3
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BigCommerce Channels API
 *
 * The Channels API enables you to create and manage listings across a BigCommerce merchant's sales channels.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BigCommerce\Api\v3\Model;

use \ArrayAccess;

/**
 * UpdateListingRequest Class Doc Comment
 *
 * @category    Class */
/**
 * @package     BigCommerce\Api\v3
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdateListingRequest implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'UpdateListingRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'listing_id' => 'int',
        'channel_id' => 'int',
        'product_id' => 'int',
        'state' => 'string',
        'name' => 'string',
        'description' => 'string',
        'external_id' => 'string',
        'variants' => '\BigCommerce\Api\v3\Model\CreateOrUpdateVariantRequest[]'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'listing_id' => 'listing_id',
        'channel_id' => 'channel_id',
        'product_id' => 'product_id',
        'state' => 'state',
        'name' => 'name',
        'description' => 'description',
        'external_id' => 'external_id',
        'variants' => 'variants'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'listing_id' => 'setListingId',
        'channel_id' => 'setChannelId',
        'product_id' => 'setProductId',
        'state' => 'setState',
        'name' => 'setName',
        'description' => 'setDescription',
        'external_id' => 'setExternalId',
        'variants' => 'setVariants'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'listing_id' => 'getListingId',
        'channel_id' => 'getChannelId',
        'product_id' => 'getProductId',
        'state' => 'getState',
        'name' => 'getName',
        'description' => 'getDescription',
        'external_id' => 'getExternalId',
        'variants' => 'getVariants'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const STATE_ACTIVE_GROUP = 'ACTIVE_GROUP';
    const STATE_DISABLED_GROUP = 'DISABLED_GROUP';
    const STATE_ERRORED_GROUP = 'ERRORED_GROUP';
    const STATE_PENDING_GROUP = 'PENDING_GROUP';
    const STATE_PENDING_DISABLE_GROUP = 'PENDING_DISABLE_GROUP';
    const STATE_PENDING_DELETE_GROUP = 'PENDING_DELETE_GROUP';
    const STATE_QUEUED_GROUP = 'QUEUED_GROUP';
    const STATE_REJECTED_GROUP = 'REJECTED_GROUP';
    const STATE_SUBMITTED_GROUP = 'SUBMITTED_GROUP';
    const STATE_DELETED_GROUP = 'DELETED_GROUP';
    const STATE_UNKNOWN_LISTING_GROUP_STATE = 'UNKNOWN_LISTING_GROUP_STATE';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getStateAllowableValues()
    {
        return [
            self::STATE_ACTIVE_GROUP,
            self::STATE_DISABLED_GROUP,
            self::STATE_ERRORED_GROUP,
            self::STATE_PENDING_GROUP,
            self::STATE_PENDING_DISABLE_GROUP,
            self::STATE_PENDING_DELETE_GROUP,
            self::STATE_QUEUED_GROUP,
            self::STATE_REJECTED_GROUP,
            self::STATE_SUBMITTED_GROUP,
            self::STATE_DELETED_GROUP,
            self::STATE_UNKNOWN_LISTING_GROUP_STATE,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['listing_id'] = isset($data['listing_id']) ? $data['listing_id'] : null;
        $this->container['channel_id'] = isset($data['channel_id']) ? $data['channel_id'] : null;
        $this->container['product_id'] = isset($data['product_id']) ? $data['product_id'] : null;
        $this->container['state'] = isset($data['state']) ? $data['state'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['external_id'] = isset($data['external_id']) ? $data['external_id'] : null;
        $this->container['variants'] = isset($data['variants']) ? $data['variants'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];
        if ($this->container['listing_id'] === null) {
            $invalid_properties[] = "'listing_id' can't be null";
        }
        if ($this->container['product_id'] === null) {
            $invalid_properties[] = "'product_id' can't be null";
        }
        if ($this->container['state'] === null) {
            $invalid_properties[] = "'state' can't be null";
        }
        $allowed_values = ["ACTIVE_GROUP", "DISABLED_GROUP", "ERRORED_GROUP", "PENDING_GROUP", "PENDING_DISABLE_GROUP", "PENDING_DELETE_GROUP", "QUEUED_GROUP", "REJECTED_GROUP", "SUBMITTED_GROUP", "DELETED_GROUP", "UNKNOWN_LISTING_GROUP_STATE"];
        if (!in_array($this->container['state'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'state', must be one of #{allowed_values}.";
        }

        if ($this->container['variants'] === null) {
            $invalid_properties[] = "'variants' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['listing_id'] === null) {
            return false;
        }
        if ($this->container['product_id'] === null) {
            return false;
        }
        if ($this->container['state'] === null) {
            return false;
        }
        $allowed_values = ["ACTIVE_GROUP", "DISABLED_GROUP", "ERRORED_GROUP", "PENDING_GROUP", "PENDING_DISABLE_GROUP", "PENDING_DELETE_GROUP", "QUEUED_GROUP", "REJECTED_GROUP", "SUBMITTED_GROUP", "DELETED_GROUP", "UNKNOWN_LISTING_GROUP_STATE"];
        if (!in_array($this->container['state'], $allowed_values)) {
            return false;
        }
        if ($this->container['variants'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets listing_id
     * @return int
     */
    public function getListingId()
    {
        return $this->container['listing_id'];
    }

    /**
     * Sets listing_id
     * @param int $listing_id
     * @return $this
     */
    public function setListingId($listing_id)
    {
        $this->container['listing_id'] = $listing_id;

        return $this;
    }

    /**
     * Gets channel_id
     * @return int
     */
    public function getChannelId()
    {
        return $this->container['channel_id'];
    }

    /**
     * Sets channel_id
     * @param int $channel_id
     * @return $this
     */
    public function setChannelId($channel_id)
    {
        $this->container['channel_id'] = $channel_id;

        return $this;
    }

    /**
     * Gets product_id
     * @return int
     */
    public function getProductId()
    {
        return $this->container['product_id'];
    }

    /**
     * Sets product_id
     * @param int $product_id
     * @return $this
     */
    public function setProductId($product_id)
    {
        $this->container['product_id'] = $product_id;

        return $this;
    }

    /**
     * Gets state
     * @return string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     * @param string $state
     * @return $this
     */
    public function setState($state)
    {
        $allowed_values = array('ACTIVE_GROUP', 'DISABLED_GROUP', 'ERRORED_GROUP', 'PENDING_GROUP', 'PENDING_DISABLE_GROUP', 'PENDING_DELETE_GROUP', 'QUEUED_GROUP', 'REJECTED_GROUP', 'SUBMITTED_GROUP', 'DELETED_GROUP', 'UNKNOWN_LISTING_GROUP_STATE');
        if ((!in_array($state, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'state', must be one of 'ACTIVE_GROUP', 'DISABLED_GROUP', 'ERRORED_GROUP', 'PENDING_GROUP', 'PENDING_DISABLE_GROUP', 'PENDING_DELETE_GROUP', 'QUEUED_GROUP', 'REJECTED_GROUP', 'SUBMITTED_GROUP', 'DELETED_GROUP', 'UNKNOWN_LISTING_GROUP_STATE'");
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     * @param string $description
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets external_id
     * @return string
     */
    public function getExternalId()
    {
        return $this->container['external_id'];
    }

    /**
     * Sets external_id
     * @param string $external_id
     * @return $this
     */
    public function setExternalId($external_id)
    {
        $this->container['external_id'] = $external_id;

        return $this;
    }

    /**
     * Gets variants
     * @return \BigCommerce\Api\v3\Model\CreateOrUpdateVariantRequest[]
     */
    public function getVariants()
    {
        return $this->container['variants'];
    }

    /**
     * Sets variants
     * @param \BigCommerce\Api\v3\Model\CreateOrUpdateVariantRequest[] $variants
     * @return $this
     */
    public function setVariants($variants)
    {
        $this->container['variants'] = $variants;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\BigCommerce\Api\v3\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\BigCommerce\Api\v3\ObjectSerializer::sanitizeForSerialization($this));
    }
}


